M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-06-03T20:12:11+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-03T20:12:11+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.388Y-3.2524
X4.388Y-3.4799
M30
